# Site settings
author: Serhiy Bardysh
title: My online journey to become Full Stack Developer one day at a time  
header-img: img/home-bg.png
email: sbardysh@tutanota.com
copyright_name: Serhiy Bardysh
description: > # this means to ignore newlines until "baseurl:"
  CLI Project, my first project from scratch.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  DabooUA

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
